### ISSUE TITLE
"On player spawn" is actually triggering on player respawn

### ISSUE THREAD

**Issue by flo** [Terasology/Scenario#24]
*Current situation:*
* There is one event called "On player spawn" that triggers when the player respawns

*Target situation:*
* There are 2 selectable events instead of 1:
  * On player respawn, that triggers when a player character respawns (event class `OnPlayerRespawnedEvent`)
  * On player spawn, that triggers when a player character spawns for the first time (event class `OnPlayerSpawnedEvent`)

**Comment by skaldarnar** [comment]
What exactly would be covered by OnPlayerSpawn? Is it the first spawn after
connecting to the server, e.g. not respawning from within the running world
instance?

flo <notifications@github.com> schrieb am Do. 29. Juni 2017 um 22:31:

**Comment by flo** [comment]
yes, I belief so

**Comment by flo** [comment]
Implemented
